version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 2527
      MYSQL_DATABASE: myapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 2527
    ports:
      - "9906:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      backend:
        aliases:
          - db
  web:
    image: tut:php_img
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8888:80"
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - web-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8101:80"
    restart: always
    networks:
      backend:
        aliases:
          - phpmyadmin

networks:
  backend:
volumes:
  db-volume:
